name: 'My TypeScript Action'
description: 'A simple TypeScript action that greets the user.'
inputs:
  name:
    description: 'The name of the person to greet'
    required: true
    default: 'World'
outputs:
  greeting:
    description: 'The greeting message'
runs:
  using: 'node12'
  main: 'dist/index.js'
