name: Call REST API method

on:
  workflow_dispatch:

env:
  SERVICE_URL: http://localhost:7070
defaults:
  run:
    shell: pwsh
    #working-directory: ..\

jobs:
  send_data:
    runs-on: self-hosted
    steps:
      - name: Send Data to REST WS
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SERVICE_URL: ${{ secrets.SERVICE_URL }}
        run: |
          response=$(curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $SECRET_KEY" \
            -d "{\"data\":\"https://github.com/dorin7bogdan/uft-one-tests/\"}" \
            "$SERVICE_URL/repo/validate")

          echo "Response: $response"

#  dump_contexts_to_log:
#    runs-on: self-hosted
#    steps:
#      - name: Dump GitHub context
#        id: github_context_step
#        run: echo '${{ toJSON(github) }}'
#      - name: Dump job context
#        run: echo '${{ toJSON(job) }}'
#      - name: Dump steps context
#        run: echo '${{ toJSON(steps) }}'
#      - name: Dump runner context
#        run: echo '${{ toJSON(runner) }}'
#      - name: Dump strategy context
#        run: echo '${{ toJSON(strategy) }}'
#      - name: Dump matrix context
#        run: echo '${{ toJSON(matrix) }}'

