name: Manual workflow 2

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:

env:
  PROPS_TXT: PropsMultiTests.txt
  RES_XML: ResultsMultiTests.xml
  LAUNCHER_EXE: FTToolsLauncher.exe
  LAUNCHER_URL: https://github.com/MicroFocus/ADM-FT-ToolsLauncher/releases/download/v1.0-beta-rev12/FTToolsLauncher_net48.exe
defaults:
  run:
    shell: pwsh
    working-directory: $env:GITHUB_WORKSPACE\..

jobs:
  getUftOneTests:
    runs-on: self-hosted
    steps:
    - name: Display the working folder
      run: echo "$env:GITHUB_WORKSPACE"
    - name: Checkout current repo
      uses: actions/checkout@v3
      with:
        ref: ${{github.ref_name}}

  createPropsFile:
    runs-on: self-hosted
    needs: getUftOneTests
    steps:
    - name: Create properies file
      run: |
        @"
        runType=FileSystem
        Test1=$($pwd.Path.Replace('\', '\\'))
        resultsFilename=$env:RES_XML
        "@ > $env:PROPS_TXT
    - name: Check properies file
      run: TEST-PATH $env:PROPS_TXT
