name: Call REST API method

on:
  workflow_dispatch:

env:
  SERVICE_URL: http://localhost:7070
defaults:
  run:
    shell: pwsh
    #working-directory: ..\

jobs:
  send_data:
    runs-on: self-hosted
    steps:
      - name: Send Data to REST WS
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          VE_TENANT_ID: 129005
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
        run: |
          $body = @{
            url = $env:REPO_URL
          } | ConvertTo-Json

          $headers = @{
            'Content-Type' = 'application/json'
            'X-VE-TENANT-ID' = "$env:VE_TENANT_ID"
          }

          $response = Invoke-RestMethod `
            -Method Post `
            -Uri "$env:SERVICE_URL/repo/validate" `
            -Headers $headers `
            -Body $body

          Write-Output "Response: $response"

          if ($LASTEXITCODE -ne 0) {
            Write-Error "Error calling web service"
            exit 1
          }

#  dump_contexts_to_log:
#    runs-on: self-hosted
#    steps:
#      - name: Dump GitHub context
#        id: github_context_step
#        run: echo '${{ toJSON(github) }}'
#      - name: Dump job context
#        run: echo '${{ toJSON(job) }}'
#      - name: Dump steps context
#        run: echo '${{ toJSON(steps) }}'
#      - name: Dump runner context
#        run: echo '${{ toJSON(runner) }}'
#      - name: Dump strategy context
#        run: echo '${{ toJSON(strategy) }}'
#      - name: Dump matrix context
#        run: echo '${{ toJSON(matrix) }}'

