name: Manual workflow 3

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:

env:
  PROPS_TXT: PropsMultiTests.txt
  RES_XML: ResultsMultiTests.xml
  LAUNCHER_EXE: FTToolsLauncher.exe
  LAUNCHER_URL: https://github.com/MicroFocus/ADM-FT-ToolsLauncher/releases/download/v1.0-beta-rev12/FTToolsLauncher_net48.exe
defaults:
  run:
    shell: pwsh
    working-directory: ..\

jobs:
  checkFTToolsLauncher:
    runs-on: self-hosted
    needs: getFTToolsLauncher
    steps:
    - name: CHECK FTToolsLauncher.exe
      run:  if (TEST-PATH $env:LAUNCHER_EXE) {
              Write-Host 'FTToolsLauncher.exe is available' 
            } else {
              Write-Error 'FTToolsLauncher.exe not found' 
            }
    - run: $x = -2
    - run: Write-Error "Process completed with exit code $x"
