name: Manual workflow 3

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:

env:
  X: 0
  PROPS_TXT: PropsMultiTests.txt
  RES_XML: ResultsMultiTests.xml
  LAUNCHER_EXE: FTToolsLauncher.exe
  LAUNCHER_URL: https://github.com/MicroFocus/ADM-FT-ToolsLauncher/releases/download/v1.0-beta-rev12/FTToolsLauncher_net48.exe
defaults:
  run:
    shell: pwsh
    working-directory: ..\

jobs:
  checkFTToolsLauncher:
    runs-on: self-hosted
    steps:
    - run: $env:X = -2
    - run: echo $env:X
    - name: End
      if: $env:X != 0
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('The job failed with status TODO !')    
