name: Manual workflow 3

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh
    working-directory: ..\

jobs:
  checkFTToolsLauncher:
    runs-on: self-hosted
    steps:
    - id: step1
      run: |
        "X=-2" >> $env:GITHUB_OUTPUT
    - run: echo "X = ${{steps.step1.outputs.X}}"
    - if: ${{steps.step1.outputs.X}} != 0
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('The job failed with status ${{steps.step1.outputs.X}} !')    
    - if: ${{steps.step1.outputs.X}} != 0
      run: Write-Error "The job failed with status ${{steps.step1.outputs.X}} !"
